spring:
  data:
    mongodb:
      uri: mongodb+srv://samnangan699:x2CLBCVJT3FLEX5CE56nHrGRqTpZsZDCP5CE@samnang-mongo.ayjpfyj.mongodb.net/oauth-database?retryWrites=true&w=majority&appName=samnang-mongo
#spring:
#  data:
#    mongodb:
#      host: https://mongodb.internal.delightfulfield-91802938.eastus.azurecontainerapps.io
#      port: 27017
#      database: oauth-database
#      username:
#      password:

security:
  oauth2:
    client:
      clientId: ankaboot
      clientSecret: ankaboot
